swagger: "2.0"
info:
  version: "0.0.1"
  title: Brackr
# during dev, should point to your local machine
host: brackr.us-west-2.elasticbeanstalk.com
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /bracket:
    # binds a127 app logic to a route
    x-swagger-router-controller: bracket
    post:
      description: Creates a new bracket
      # used as the method name of the controller
      operationId: create
      parameters:
        - in: body
          name: choices
          description: choices in the bracket
          required: true
          schema:
            type: array
            items: 
              type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CreateBracketResponse"
  /bracket/{id}:
    x-swagger-router-controller: bracket
    get:
      description: Gets an existing bracket by id
      # used as the method name of the controller
      operationId: get
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CreateBracketResponse"
  /bracket/{id}/next:
    x-swagger-router-controller: bracket
    post:
      description: Re-runs the bracket to get the best remaining choice
      # used as the method name of the controller
      operationId: rerun
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CreateBracketResponse"
  /bracket/{id}/round/current:
    x-swagger-router-controller: bracket
    get:
      description: Gets an existing bracket by id
      # used as the method name of the controller
      operationId: currentRound
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/Round'
  /bracket/{id}/round/next:
    x-swagger-router-controller: bracket
    post:
      description: Gets an existing bracket by id
      # used as the method name of the controller
      operationId: close
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        "200":
          description: Success
  
  /bracket/{id}/match/{matchId}/player/{seed}:
    x-swagger-router-controller: bracket
    post:
      description: Gets an existing bracket by id
      # used as the method name of the controller
      operationId: vote
      parameters:
        - in: path
          name: id
          required: true
          type: string
        
        - in: path
          name: matchId
          required: true
          type: string
        
        - in: path
          name: seed
          required: true
          type: number
      responses:
        "200":
          description: Success
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  CreateBracketResponse:
    required:
      - id
    properties:
      id:
        type: string
      choices:
        type: array
        items:
          type: string
      results:
        type: array
        items:
          type: string

  Round:
    required:
      - currentRound
      - totalRounds
      - matches
    properties:
      currentRound:
        type: number
      totalRounds:
        type: number
      matches:
        type: array
        items:
          $ref: '#/definitions/Match'
      results:
        type: array
        items:
          type: string
  Match:
    required:
      - id
      - players
    properties:
      id:
        type: string
      players:
        type: array
        items:
          $ref: '#/definitions/MatchPlayer'

  MatchPlayer:
    required:
      - seed
      - data
    properties:
      seed:
        type: number
      data:
        type: string